trigger:
  - main

pool:
  name: Default

steps:

- checkout: self

- script: |
    java -version
  displayName: 'Check Java'

- script: |
    liquibase --version
  displayName: 'Check Liquibase'

- script: |
    liquibase \
      --changeLogFile=changelog/db.changelog-master.json \
      validate
  displayName: 'Validate Changelog'

- script: |
    liquibase \
      --changeLogFile=changelog/db.changelog-master.json \
      updateSQL
  displayName: 'Generate SQL'

- script: |
    liquibase \
      --changeLogFile=changelog/db.changelog-master.json \
      update
  displayName: 'Apply Migration'
